=== ChaoZavitkar/KI-PRI/Projekt/www/html/xml/equipment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="equipment"
           xmlns="equipment"
           elementFormDefault="qualified">
    
    <xs:element name="Equipment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Quantity" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== ChaoZavitkar/KI-PRI/Projekt/www/html/xml/equipment.xml
<?xml version="1.0" encoding="UTF-8"?>
<Equipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="equipment.xsd">
    <Item>
        <Name>Longsword</Name>
        <Quantity>1</Quantity>
    </Item>
    <Item>
        <Name>Shortbow</Name>
        <Quantity>1</Quantity>
    </Item>
    <Item>
        <Name>Arrows</Name>
        <Quantity>20</Quantity>
    </Item>
    <Item>
        <Name>Leather Armor</Name>
        <Quantity>1</Quantity>
    </Item>
    <Item>
        <Name>Staff</Name>
        <Quantity>1</Quantity>
    </Item>
    <Item>
        <Name>Spellbook</Name>
        <Quantity>1</Quantity>
    </Item>
    <Item>
        <Name>Robes</Name>
        <Quantity>1</Quantity>
    </Item>
</Equipment>
