=== ChaoZavitkar/KI-PRI/Projekt/www/html/xml/spells.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="spells"
           xmlns="spells"
           elementFormDefault="qualified">
    
    <xs:element name="Spells">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Spell" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Level" type="xs:integer"/>
                            <xs:element name="Prepared" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== ChaoZavitkar/KI-PRI/Projekt/www/html/xml/spells.xml
<?xml version="1.0" encoding="UTF-8"?>
<Spells xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="spells.xsd">
    <Spell>
        <Name>Fireball</Name>
        <Level>3</Level>
        <Prepared>true</Prepared>
    </Spell>
    <Spell>
        <Name>Shield</Name>
        <Level>1</Level>
        <Prepared>true</Prepared>
    </Spell>
    <Spell>
        <Name>Magic Missile</Name>
        <Level>1</Level>
        <Prepared>true</Prepared>
    </Spell>
    <Spell>
        <Name>Hunter's Mark</Name>
        <Level>1</Level>
        <Prepared>true</Prepared>
    </Spell>
    <Spell>
        <Name>Goodberry</Name>
        <Level>1</Level>
        <Prepared>false</Prepared>
    </Spell>
</Spells>
